### PR TITLE
Compile messages and accept the python package for Django settings

### PR DESCRIPTION
**Pull request by YazdanRa**

### CODE REVIEW

**Comment by YazdanRa** [comment]
I think we should migrate the migrations in build stage but I didn't add that yet.
add bellow line even before the `collectstatic`:
```shell
python manage.py migrate --noinput
```

**Comment by YazdanRa** [comment]
Maybe the line :
```shell
find . -name "settings.py" -o "settings/__init__.py"
```
don't work as well then we should try this one for the package files:
```shell
find */settings -name "__init__.py"
```
We can do it in a semi try-except way:
```
{ # try

} || { # except

}
```

**Comment by mhemrg** [comment]
Hi @YazdanRa,
Thanks for your PR.

I don't think using the `-o` parameter for the `find` command is a good idea.

Instead of the try/catch method, what about this:
```
find . -name 'settings.py' | grep -z . || find . -wholename "**/settings/__init__.py"
```

**Comment by YazdanRa** [comment]
It would be better
I'll fix it!

**Comment by mhemrg** [comment]
I just kinda rewrote the whole platform to meet your requirements. You can check it out here:
https://github.com/liara-cloud/django-platform/tree/add-more-options

**Comment by YazdanRa** [comment]
Thanks for your consideration,

I reviewed that branch and I think now it's much better than before.

you can add the code box bellow to your entrypoint:

```
echo Waiting for database...
echo DB_DATABASE: ${DB_DATABASE}
echo DB_HOST: ${DB_HOST}
echo DB_PORT: ${DB_PORT}
while ! nc -z ${DB_HOST} ${DB_PORT}; do sleep 1; done
echo Connected to database.
```

to make sure the datadabe is connected before doing rest of the code!

in some states it's possible that the database pod/replica is not ready yet or faced with an error.

**Comment by YazdanRa** [comment]
Besides, add a feature for migrate db in `entrypoint.sh` is possible now!

**Comment by mhemrg** [comment]
Hey @YazdanRa, thanks for your helpful insights.
Doing database related stuff in the build time is a bit challenging and we're trying to avoid it because it's not a best practice.
We're going to put these new changes into production, soon. We'll be more than happy if you try the new image by creating an app on console.liara.ir and let us know your thoughts.

**Comment by mhemrg** [comment]
To find the settings file, we're using a new approach. Instead of finding a `settings.py` file, we're looking for a `WSGI_APPLICATION` variable. The file which contains this variable would be our `settings.py` file, no matter what's its name.
Do you think the method will work in most projects?

**Comment by YazdanRa** [comment]
Absolutely, I will do that. It's my pleasure.
The new changes are perfect, I'm looking forward to test them.
Congrats dear @mhemrg for your great platform.

**Comment by mhemrg** [comment]
Improving it without your insights wouldn't be possible.
For now, I'm closing this issue. I'll let you know when it was ready to test.
Thanks for your contribution.

**Comment by mhemrg** [comment]
Deployed to production now:
https://docs.liara.ir/app-deploy/django/tips

**Comment by YazdanRa** [comment]
I checked them out, it's now much better than before!
We can customize our building stage and those are interesting features.
Thanks a lot for your consideration.

**Pull request closed without merging**
